### ISSUE TITLE
Updates endpoint returns a 500 error

### ISSUE THREAD

**Issue by fastlinemedia** [beaverbuilder/assistant#147]
The endpoint to read updates is returning a 500 error in the `new-ui` branch. Here's the endpoint I'm having an issue with...

`http://localhost/wp-json/fl-assistant/v1/updates?offset=0&updateType=all&number=20`

My PHP error logs don't show anything. Here's the full response...

`{"code":"rest_invalid_handler","message":"The handler for the route is invalid","data":{"status":500}}`

**Comment by phredeye** [comment]
Failed to remove some scope resolution operators "::" from register_routes.  These are fixed.  Also added a phpunit test for UpdatesController
