### ISSUE TITLE
Unique key error with List component

### ISSUE THREAD

**Issue by fastlinemedia** [beaverbuilder/assistant#148]
The console shows a "unique key" error when using the `<List />` component. This only seems to be the case with `getItemProps`. When that is removed, the error goes away. 
> react.development.js:188 Warning: Each child in a list should have a unique "key" prop.
> 
> Check the render method of `List`. See https://fb.me/react-warning-keys for more information.

You can currently see the error on the Alerts > Comments tab in the `new-ui` branch.

**Comment by brentjett** [comment]
Yep, cause one of the props you're supposed to return is the item key.
The callback will give you a few arguments to help here:
```
<List
    items={items}
    getItemProps={ ( item, defaultProps, isSection ) => {

        // The defaultProps object already contains `key: i` and you can use it
        let props = { ...defaultProps }

        // But if you wanted to, you could set a custom key, like:
        props.key = item.postID

        return props
    }}
/>
```

**Comment by fastlinemedia** [comment]
Looks like the key is there :) 

```
<List
	items={comments}
	getItemProps={ (item, i) => {
		return {
			key: item.postID,
			label: <em><strong>{item.email}</strong> commented:</em>,
			description: item.content,
			thumbnail: item.thumbnail,
			to: {
				pathname: `${baseURL}/comments/${item.postID}`,
				state: item
			}
		}
	}}
/>
```

**Comment by brentjett** [comment]
but the args aren't quite right. `getItemProps` args are `(item, defaultProps, isSection) => {}`
so what you want is (I just pushed this fix for the comments app btw)
```
getItemProps={ (item, defaultProps) => {
    return {
        key: defaultProps.key // this is where you get i from
    }
} }
```

**Comment by brentjett** [comment]
I just saw `key: i ` in the code. You sure you had item.postID values on that comment list?

**Comment by fastlinemedia** [comment]
Ah, maybe I copy/pasted from somewhere incorrectly. Can I just omit the key?

**Comment by brentjett** [comment]
The props object you return has to have a key included, but if you just include `defaultProps` you'll have that.
`return { ...defaultProps }`

**Comment by fastlinemedia** [comment]
Ah perfect, thanks!

**Comment by brentjett** [comment]
Pretty sure we're past this one, so i'm closing.
