### ISSUE TITLE
Gutenberg errors out when Assistant is active AND featured image section is open.

### ISSUE THREAD

**Issue by brentjett** [beaverbuilder/assistant#160]
When using Assistant over Gutenberg, as soon as you open the Featured Image section the document sidebar, the whole Gutenberg application errors out. Looks like it might be related to lodash.

Current workaround involves deactivating Assistant plugin, closing the featured image section, and reactivating Assistant.

**Comment by fastlinemedia** [comment]
This appears to be resolved in the latest `new-ui` branch.
