### ISSUE TITLE
useScrollLoader no longer working

### ISSUE THREAD

**Issue by fastlinemedia** [beaverbuilder/assistant#164]
The `has_more` flag is now being included in REST responses, however, scroll pagination still doesn't seem to be working. It looks like something might have changed with scrolling since this was last working and I believe it has to do with overflow of the divs and `useScrollLoader`. 

I tested this in `useScrollLoader` be simply logging in the scroll callback. It doesn't seem to be firing when I scroll a list as `HERE 2` is never logged. It does look like the listener is being added as `HERE 1` is logged...

https://cl.ly/ef569e1033fc

**Comment by brentjett** [comment]
`.fl-page-content` was missing `max-width: 100%` causing it not to overflow. Fixed.
