### ISSUE TITLE
Comments App

### ISSUE THREAD

**Issue by fastlinemedia** [beaverbuilder/assistant#169]
Final round of work on the comments app for 0.3.

**Comment by fastlinemedia** [comment]
See PR #168

**Comment by fastlinemedia** [comment]
@shahidajmeri786 can you merge `new-ui` into this branch? I believe there is some work on the Page component that fixes a few issues you were facing. 

@brentjett is it possible to attach the Message component to the Page component now? 

Also, I'm seeing some extra space on the list...

https://share.getcloudapp.com/WnuEk8lJ

Can you let us know how to handle that?

**Comment by shahidajmeri786** [comment]
@fastlinemedia  and @brentjett 
I merged and I see some UI related changes. but I also notice that the list of extra items is now not showing.
When we hover over the list before there are list extra icons displayed but after merge it is not working.
However, same is also not working in the content app when we see a list of post and hover over an item.
I pushed the code after the merge. Can you please check?
