### ISSUE TITLE
Beaver Builder integration

### ISSUE THREAD

**Issue by fastlinemedia** [beaverbuilder/assistant#171]
Audit the Beaver Builder integration to see what is left to finish.

- Get BB updated to the latest FLUID build
- See if anything is needed in the toolbar
- Do something about older versions of WP that don’t include react/react-dom
- Test

**Comment by brentjett** [comment]
- [ ]  Add Icon to toolbar
- [ ]  Fix dark mode handling
- [ ]  Check that panel hides when appropriate.
