### ISSUE TITLE
Media App: Refactor detail view

### ISSUE THREAD

**Issue by fastlinemedia** [beaverbuilder/assistant#176]
- [x] Refactor the detail view of the media app using the `Form.useForm` hook.
- [x] Hook up all form fields to the backend.
- [x] Add file size, upload date, and type
- [x] Add delete action

**Comment by shahidajmeri786** [comment]
Refactored the detail view of the media app using the Form.useForm hook.
Hooked up all form fields to the backend.
Added file size, upload date, and type
added delete action
