### ISSUE TITLE
Notices UI

### ISSUE THREAD

**Issue by fastlinemedia** [beaverbuilder/assistant#188]
Mockups for the UI that will allow for native Assistant notifications instead of using `alert`.

**Comment by brentjett** [comment]
Here's an outline of the notice component. I'll probably implement this along with a `useNotices()` hook to manage state.

<img width="407" alt="Screen Shot 2020-04-01 at 6 27 39 PM" src="https://user-images.githubusercontent.com/1790660/78196031-c6333980-7446-11ea-821d-878bd435c962.png">

Placement for notices will be implemented through a new prop on `Page`. More details on the API to come.

<img width="1194" alt="Screen Shot 2020-04-01 at 6 30 45 PM" src="https://user-images.githubusercontent.com/1790660/78196068-e9f67f80-7446-11ea-8449-1087032f4df5.png">
