### ISSUE TITLE
"Nothing Found" component renders extra zero

### ISSUE THREAD

**Issue by brentjett** [beaverbuilder/assistant#198]
The `List.NoResultsMessage` component is rendering a zero after its content. This can be found in `system/ui/parts`.
![image](https://user-images.githubusercontent.com/1790660/73851328-e651ce00-47f2-11ea-8db6-df2c64c00a77.png)

**Comment by fastlinemedia** [comment]
Fixed in the updates PR by @shahidajmeri786. Thanks!
