### ISSUE TITLE
Feature: Add Featured Image Editing to Post Detail View

### ISSUE THREAD

**Issue by brentjett** [beaverbuilder/assistant#199]
Make it possible to replace, remove and add featured images on the post detail screen for post types that support it.

**Comment by shahidajmeri786** [comment]
**Things have done:**
Upload feature image
Store feature image
Display feature image
**Pending:**
Remove feature image
You can quickly view here: https://www.screencast.com/t/3w2a04Ad

**Comment by shahidajmeri786** [comment]
Added remove feature image. pushed code into post-feature-image-branch"
