### ISSUE TITLE
Assistant Home: Email Opt-in Form

### ISSUE THREAD

**Issue by fastlinemedia** [beaverbuilder/assistant#204]
We'd like to create a simple email opt-in form on the Assistant home screen. Something like this should be a good place to start...

https://share.getcloudapp.com/BluB7xnP

This form will be connected to Drip.

**Comment by shahidajmeri786** [comment]
Added form for subscribing with validation and integrated Drip API to register the subscriber  tag "Assistant newsletter" 
Refer here for quick view how its work : https://www.screencast.com/t/GUbD6Ikw6xql
Do let me know necessary changes if required.
