### ISSUE TITLE
Post Detail: Hook up publish date for editing

### ISSUE THREAD

**Issue by fastlinemedia** [beaverbuilder/assistant#221]
Hook up the publish date in the post detail view so it can be edited. This will likely involve installing a calendar component. Let's start with researching those and see what @brentjett approves of.

**Comment by shahidajmeri786** [comment]
Hi @fastlinemedia :
I added one react-date picker component and integrated it as a form component 'calendar'.
The calendar is working fine but I am not getting date value from the form data.

It giving me 'undefined' as the value of the field. although I checked the HTML and HTML has proper value field and also checked 'use-form-data' but they also respond filed with undefined as value.

I pushed code. so can you help me what's wrong I did?

for reference :

![image](https://user-images.githubusercontent.com/50620598/78259793-c43aaa80-751a-11ea-9c4c-f1a4df08d3a3.png)

![image](https://user-images.githubusercontent.com/50620598/78259821-cf8dd600-751a-11ea-8c77-a5a5ede56e10.png)

![image](https://user-images.githubusercontent.com/50620598/78259847-d87ea780-751a-11ea-9692-3b9c18f4ae10.png)

**Comment by fastlinemedia** [comment]
Hey @shahidajmeri786 it looks like the issue is that you're passing `setStartDate(date)` to the `onChange` callback. That callback should be passed the value, not the return of a state setter...

```
onChange={date => {
  setStartDate(date)
  onChange(date)
}}
```

I was chatting with Brent about the date picker component. In an effort to try and keep the bundle size down, let's look to `@wordpress/components` before going elsewhere. 

https://www.npmjs.com/package/@wordpress/components

That package has a `DateTimePicker` component. Can you look at using that one instead? 

Thanks!
