### ISSUE TITLE
Assistant icon in the Beaver Builder page editor that appears to do nothing

### ISSUE THREAD

**Issue by DavidWaumsley** [beaverbuilder/assistant#240]
I expect it is there for later plans, but is presently in the WP repo version.

https://cloud.wpcornershop.com/qGuo80oE

**Comment by brentjett** [comment]
yea that's a slip on our end. That icon is meant to be paired with the upcoming Beaver Builder 2.4 release. We'll be removing it from Assistant in a fix release.

**Comment by DavidWaumsley** [comment]
Great thanks, Brent. I completely missed there was Alpha out.

**Comment by brentjett** [comment]
Fixed in 0.3.1
