### ISSUE TITLE
21 extra front end database queries 

### ISSUE THREAD

**Issue by DavidWaumsley** [beaverbuilder/assistant#241]
I just wondered about performance?

According to the query monitor plugin ( on the site I am testing) there were 21 extra database queries added to front end pages on activating Assistant.

**Comment by brentjett** [comment]
The majority of those are simply counting various things, like totals for each post type. Most of our data is loaded asynchronously via the WP REST API. We'll take a look, though, and see where we can tighten this up. Thanks!

**Comment by brentjett** [comment]
Also if you look at the elapsed time for each of those, they're incredibly short. The longest on my test site is `0.0008` sec.

**Comment by DavidWaumsley** [comment]
Thanks so much for this quick response, Brent. It's good to hear. I really don't have the tools or skills to monitor these things appropriately, but as you probably know, I love all things by you guys. 

It has helped me much watching these things, but I guess things are less straightforward with the WP REST API.
