### ISSUE TITLE
Feature request: Option to quick edit pages/posts and meta fields

### ISSUE THREAD

**Issue by Bobolinos** [beaverbuilder/assistant#259]
Also change things like the author of a post/page quickly from within assistant without going to the page itself.
+Quick edit Yoast title / meta description

**Comment by Bobolinos** [comment]
Also change things like the author of a post/page quickly from within assistant without going to the page itself.

**Comment by Bobolinos** [comment]
+Quick edit Yoast title / meta description

**Comment by brentjett** [comment]
Author field is on our radar. Custom field integration with other plugins will be the topic of a future release. #202
