### ISSUE TITLE
Plugin not working on WPEngine

### ISSUE THREAD

**Issue by rhud** [beaverbuilder/assistant#278]
I can't get this plugin to work at all on any site hosted with WP Engine. 
I've tested with 2020 theme and no other active plugins - still no luck. No errors or warnings in console, just not there. The tool doesn't work in admin either. 
It works fine on my local dev server with the exact same setup.
Happy to share admin with a developer if it helps.
Test site: https://hhblueprint.wpengine.com/
Any thoughts?

**Comment by lopesval** [comment]
Same issue here...
Wpengine...
Even with bbtheme

**Comment by fastlinemedia** [comment]
@rhud thanks for reporting this. We'll have a fix out this week.
