### ISSUE TITLE
After 0.4.1 update, BB icon missing on App view

### ISSUE THREAD

**Issue by codente** [beaverbuilder/assistant#281]
0.4.0

<img width="268" alt="Image 2020-05-14 at 8 13 20 AM" src="https://user-images.githubusercontent.com/2265866/81949912-f8e55b80-95c8-11ea-865b-0ef1b58cfd72.png">

0.4.1
<img width="357" alt="Image 2020-05-14 at 8 13 41 AM" src="https://user-images.githubusercontent.com/2265866/81950059-19151a80-95c9-11ea-9dfe-1de3f1dc2c2d.png">

It IS still present in the detail view.

**Comment by fastlinemedia** [comment]
Well get a hotfix for this out soon, thanks!
