### ISSUE TITLE
Libraries: Endpoint for saving a post

### ISSUE THREAD

**Issue by fastlinemedia** [beaverbuilder/assistant#289]
Create a REST endpoint in the `CloudPostsController` class for saving a post to a library. 

This endpoint will be using our new backend cloud client located at `FL\Assistant\Clients\Cloud\CloudClient`.

I have created an example `save_to_library` method for you in the `PostsController` class. You can move that to `CloudPostsController` as a starting point. Please make sure all old/test cloud methods are removed from `PostsController`.

The `$client->libraries->createItem` method you will be using takes a library id and an array of the following data...

`name` - the name of the library item
`type` - the type of library item
`data` - any extra data for the item (post data in this case)
`media` - any media you'd like to upload for the item (we'll handle this later)

That should look something like this...

```
$client->libraries->createItem( $library_id,
	[
		'name' => $post->post_title,
		'type' => 'post',
		'data' => [
			'post' => $post,
			'meta' => $meta,
			'terms' => $terms,
		],
	]
);
```

To test this endpoint, you can use the new library item form located under `src/apps/fl-cloud/pages/libraries/items/post/new-post.js`

Here is an example of what your onSubmit function might look like in that file...

```
const onSubmit = ( { values, setErrors } ) => {
	const { slug } = values
	const post = posts.filter( post => post.slug === slug ).pop()
	wpRest.posts().saveToLibrary( post.id, libraryId ).then( response => {
		onCreate()
	} ).catch( error => {
		setErrors( error.response.data.errors )
	} )
}
```

**Comment by shahidajmeri786** [comment]
Worked on saving to library task. the post/page data are now storing to the cloud when user add new post/page into the library.
The data format for storing into the cloud is the same as you mentioned. #294
