### ISSUE TITLE
Libraries: Endpoint for overriding an existing post

### ISSUE THREAD

**Issue by fastlinemedia** [beaverbuilder/assistant#291]
Create a REST endpoint in the `CloudPostsController` class for overriding an existing post on the WP site with a library post. Overriding a post means all data, meta and terms from the library post will replace the WP post. 

This endpoint will be using our new backend cloud client located at `FL\Assistant\Clients\Cloud\CloudClient`.

For this endpoint, you'll need to create an `override_from_library` method on the `CloudPostsController`. You will pass a library item ID to this endpoint and then use the backend client to pull the item data. That method should look something like this...

```
function override_from_library( $request ) {
	$item_id = $request->get_param( 'item_id' );
	$client = new \FL\Assistant\Clients\Cloud\CloudClient;
	$response = $client->libraries->getItem( $item_id );

	// Logic to override the post item goes. Data is in $response.
}
```

You can test that endpoint using the button here... https://share.getcloudapp.com/yAuY0png

I know the screenshot mentions options for meta and terms, but let's keep this simple for now and just focus on overriding everything. We can open another issue for that feature. 

When that button is clicked, the library post should override the current post that you are viewing.

**Comment by shahidajmeri786** [comment]
User can override the selected post/page to the library item. Currently, I gave content and terms as an option for an override. I do not give meta as an option because for beaver builder the metadata must be imported to get the page working.
#294
