### ISSUE TITLE
@beaverbuilder/fluid buttons have no type and default to submit

### ISSUE THREAD

**Issue by fastlinemedia** [beaverbuilder/assistant#312]
When you press enter within an input field, buttons in our forms are being triggered. It turns out if a button doesn't have `type="button"` defined, it will default to `type="submit"`. 

https://stackoverflow.com/questions/4763638/enter-triggers-button-click

Can we have fluid buttons be updated to default to `type="button"` to prevent this from happening when a button is in a form?

**Comment by brentjett** [comment]
Do we want this fix in `master` or `cloud`? @fastlinemedia

**Comment by brentjett** [comment]
Fixed in `cloud` branch.
