### ISSUE TITLE
Translation: User commented that translation efforts aren't working

### ISSUE THREAD

**Issue by brentjett** [beaverbuilder/assistant#321]
A WP support forum user says translation isn't working. I know we're wrapping strings for i18n in our JS but not sure how it should be working from there. Will check with team for guidance on this.

> Hi! Despite having translated the 276 strings of the plugin into Spanish, the translation is not carried out in the WordPress installation.
On the other hand, when trying to do it with LocoTranslate and syncing the template it finds, it reduces the 276 strings only to 38 strings, the rest deletes them … but still the plugin remains untranslated.

Support Thread - https://wordpress.org/support/topic/the-plugin-is-not-translated-2/

**Comment by Pross** [comment]
See https://translate.wordpress.org/projects/wp-plugins/assistant/ wporg uses assistant as the textdomain so we need to do the same for any of to work.
