### ISSUE TITLE
PHP Notice: Undefined Index..

### ISSUE THREAD

**Issue by nomad411** [beaverbuilder/assistant#373]
I saw an endless amount of log entries recently in a debug.log file.

`[22-Feb-2022 13:17:53 UTC] PHP Notice:  Undefined index: filesizeHumanReadable in /kunden/618816_22305/webseiten/wp-content/plugins/assistant/backend/src/Data/Transformers/AttachmentTransformer.php on line 32`

**Comment by codente** [comment]
Can no longer replicate so closing
