### ISSUE TITLE
Sorting libraries is not working

### ISSUE THREAD

**Issue by codente** [beaverbuilder/assistant#396]
This should be descending order by title, but it doesn't work.  Ascending does not either.   It doesn't look like any of the sorting options are working to me.

<img width="465" alt="CleanShot 2022-06-21 at 21 18 33@2x" src="https://user-images.githubusercontent.com/2265866/174929272-867b8fdc-3ee7-4ec3-a5b6-31d466cc0134.png">

**Comment by fastlinemedia** [comment]
Looks like this is an API issue after all.
