### ISSUE TITLE
Issue with permissions?

### ISSUE THREAD

**Issue by nomad411** [beaverbuilder/assistant#460]
I’ve created a Private library as a Pro user. 

I then invited another user to “View” only, following the instructions here: https://docs.wpbeaverbuilder.com/assistant/cloud/libraries/share-library

When I log in as that View-Only user, I can add posts, even a Themer layout to the library, which I can also see as the library owner.

But the themer layout ends up busted, like this: 
![i5CT6Vv66L1w8tFoLCkLnhZmlWxnuPaBGMTrs5Mp](https://github.com/beaverbuilder/assistant/assets/1724089/00a2fcf7-cc1c-484e-bdd1-ac7c2a6524f7)

**Comment by brian-flm** [comment]
In the database it's showing that all the library items in `27109` MyPrivateLibrary were created by user id `16` which is the owner of the library. 

You are logging in to the assistant plugin as the view-only user and adding posts there? 
When I try to do that on my local, the shared library doesn't show up in the list for the view user:
![image](https://github.com/beaverbuilder/assistant/assets/76957736/4fcf5020-4931-4145-b53d-534ad31b598a)

**Comment by codente** [comment]
I also tested this and I'm not able to save or add to a shared library where I'm only set to view it.

**Comment by nomad411** [comment]
Ok..  I'll come back soon with a video of my steps.  I basically had 2 users, and the "Viewer" I tested logged in in an incognito window.  Both users are Administrators on the site but that shouldn't make any difference right, it's their accounts on Assistant that matters?

**Comment by nomad411** [comment]
I've just retried and all's good, closing this
