### ISSUE TITLE
Content App: Unchecking Uncategorized results in JS error

### ISSUE THREAD

**Issue by codente** [beaverbuilder/assistant#480]
Edit a post in the content app, go to categories and uncheck Uncategorized (make sure you have more than 1 category) and you get a JS error

```
react-dom.min.js?ver=18.3.1:2 Uncaught 
TypeError: Cannot read properties of undefined (reading 'validate')
    at vendor-bb-forms.js?ver=1.4.9.2:1:6126
    at Array.map (<anonymous>)
    at _ (vendor-bb-forms.js?ver=1.4.9.2:1:6005)
    at Object.De (react-dom.min.js?ver=18.3.1:2:16716)
    at Be (react-dom.min.js?ver=18.3.1:2:16870)
    at react-dom.min.js?ver=18.3.1:2:36731
    at Ir (react-dom.min.js?ver=18.3.1:2:36825)
    at Ur (react-dom.min.js?ver=18.3.1:2:37239)
    at react-dom.min.js?ver=18.3.1:2:42667
    at ss (react-dom.min.js?ver=18.3.1:2:105954)
```

This is not new to the Code App release build.  It happens in 1.4.9.2 as well.

**Comment by brian-flm** [comment]
I'm not able to reproduce this issue with the latest version of assistant. If I uncheck `Uncategorized` I don't get any errors in the console. I don't get any errors if I click publish either.

![image](https://github.com/user-attachments/assets/349f677c-c7ce-43cd-b886-392bd717ed97)

**Comment by codente** [comment]
I also cannot reproduce. So I will close!

**Comment by codente** [comment]
New steps added to issue.

**Comment by brian-flm** [comment]
After the first save assistant adds `uuid` to the post which isn't a field that gets passed to the useForm config, so the second time the post is saved it's not able to run the validate method on `uuid`.
