### ISSUE TITLE
outdated release

### ISSUE THREAD

**Issue by prestonw** [beaverbuilder/assistant#484]
This seems an outdated release? Please update.

**Comment by codente** [comment]
Hi @prestonw what are you referring to?

**Comment by codente** [comment]
Ah, I see. You can get current versions of the plugin in the WP repo https://wordpress.org/plugins/assistant/

We stopped updating the releases here a long time ago.

**Comment by codente** [comment]
@prestonw we have now done a release here and will continue to do releases here and on the .org repo :)
